-libraryjars /home/abi/WTK2.5.2/lib/wma20.jar:/home/abi/WTK2.5.2/lib/mmapi.jar:/home/abi/WTK2.5.2/lib/midpapi20.jar:/home/abi/WTK2.5.2/lib/cldcapi10.jar
-injars /home/abi/j2mewtk/2.5.2/apps/ZaMobi/bin/ZaMobi.jar
-outjar /tmp/ZaMobi.jar
-keep public class * extends javax.microedition.midlet.MIDlet 
